\ProvidesFile{Declaration.cls}[2026/09/28 Own work declaration page]
\newcommand{\MakeDeclarationPage}{%
  \vspace*{35pt}
  \begin{center}\bfseries\fontsize{14}{18}\selectfont Own Work Declaration\end{center}
  \vspace{30pt}
  \begingroup\fontsize{12}{20.7}\selectfont\justifying\setlength{\parindent}{0pt}
  I/We acknowledge that my/our work will be examined for plagiarism or any other form
  of academic misconduct, and that the digital copy of the work may be retained for future
  comparisons.\par\vspace{20.7pt}
  I/We confirm that all sources cited in this work have been correctly acknowledged and
  that I/we fully understand the serious consequences of any intentional or unintentional
  academic misconduct.\par\vspace{20.7pt}
  In addition, I/we affirm that this submission does not contain any materials generated
  by AI tools, including direct copying and pasting of text or paraphrasing. This work is
  my/our original creation, and it has not been based on any work of other students (past
  or present), nor has it been previously submitted to any other course or institution.\par\vspace{20.7pt}
  This work is not made on any work of other students (past or present), and it has not
  been submitted to any other courses or institutions before.\par
  \vspace{69pt}Signature: \report@signature\par
  \vspace{16pt}Date: \report@date\par
  \endgroup
  \clearpage
}
\endinput
