\ProvidesFile{Report-Methods.cls}[2026/09/28 Equipment, setup and methods]
\newcommand{\ReportMethods}{%
  \report@modulebreak\Needspace{3\baselineskip}
  \noindent\textbf{Experimental Equipment, Setup, Methods}\par\nobreak\vspace{10pt}
  \ignorespaces}
\newcommand{\Hypothesis}[1]{%
  \report@modulebreak\Needspace{3\baselineskip}
  \noindent Hypothesis #1\par\nobreak\vspace{10pt}
  \ignorespaces}
\endinput
